export const DEV_ASSET_URL = import.meta.env.VITE_DEV_ASSET_URL as string;
export const MESSAGE_SEND_TO_DATA = 'X_TO_SEND_DATA';
export const MESSAGE_SEND_ASSET = 'X_SEND_ASSET';
export const MESSAGE_GENERATE_NEW = 'X_GENERATE_NEW';
export const MESSAGE_GET_ASSET_META = 'X_GET_ASSET_META';
export const MESSAGE_GET_DIGEST = 'X_GET_GET_DIGEST';
export const MESSAGE_GET_CAPTURE_IMG = 'X_GET_CAPTURE_IMG';
export const MESSAGE_SEND_DATA = 'X_SEND_DATA';
